"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var MONTH;
(function (MONTH) {
    MONTH["January"] = "01";
    MONTH["February"] = "02";
    MONTH["March"] = "03";
    MONTH["April"] = "04";
    MONTH["May"] = "05";
    MONTH["June"] = "06";
    MONTH["July"] = "07";
    MONTH["August"] = "08";
    MONTH["Sep"] = "09";
    MONTH["Oc"] = "10";
    MONTH["Nov"] = "11";
    MONTH["Dec"] = "12";
})(MONTH || (MONTH = {}));
exports.MONTH = MONTH;
var DATE;
(function (DATE) {
    DATE["January"] = "31";
    DATE["February"] = "28";
    DATE["March"] = "31";
    DATE["April"] = "30";
    DATE["May"] = "31";
    DATE["June"] = "30";
    DATE["July"] = "31";
    DATE["August"] = "31";
    DATE["Sep"] = "30";
    DATE["Oc"] = "31";
    DATE["Nov"] = "30";
    DATE["Dec"] = "31";
})(DATE || (DATE = {}));
exports.DATE = DATE;
